# Generated by Django 3.0.4 on 2020-03-08 03:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200308_0406'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='search',
            managers=[
                ('Mansouri', django.db.models.manager.Manager()),
            ],
        ),
    ]
