# Generated by Django 3.0.4 on 2020-03-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20200308_0407'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='search',
            managers=[
            ],
        ),
    ]
